// Re-export from folder-based module — do not edit this file directly.
// See CategoryForm/ for the implementation.
export { CategoryForm } from "./CategoryForm/index";
export type { CategoryFormProps } from "./CategoryForm/index";
