packages:
  - "backend"
  - "db"
  - "frontend/storefront"
  - "frontend/dashboard"
  - "frontend/ui"
  - "packages/config"
  - "packages/env"
allowBuilds:
  "@parcel/watcher": false
  "@swc/core": false
  cypress: false
  esbuild: false
  msw: false
  sharp: false
  unrs-resolver: false
