// Re-export from folder-based module — do not edit this file directly.
// See ProductTable/ for the implementation.
export { ProductTable } from './ProductTable/index';
export type { ProductTableProps, ProductFilters } from './ProductTable/index';
