// Re-export from folder-based module — do not edit this file directly.
// See FilterSidebar/ for the implementation.
export { FilterSidebar } from "./FilterSidebar/index";
export type { FilterSidebarProps } from "./FilterSidebar/index";
