// Re-export from folder-based module — do not edit this file directly.
// See CheckoutClient/ for the implementation.
export { CheckoutClient } from './CheckoutClient/index';
export type { CheckoutClientProps } from './CheckoutClient/index';
