// Re-export from folder-based module — do not edit this file directly.
// See OrderDetailControls/ for the implementation.
export { OrderDetailControls } from './OrderDetailControls/index';
export type { OrderDetailControlsProps } from './OrderDetailControls/index';
