// Re-export from folder-based module — do not edit this file directly.
// See InventoryTable/ for the implementation.
export { InventoryTable } from './InventoryTable/index';
export type { InventoryTableProps } from './InventoryTable/index';
